add first block
dmitrykorochkin/pr_Stdt pull request #1
Opened 2022-11-25 19:03 UTC by dmitrykorochkin

add first block

2022-11-25 19:38 UTC, andrey-kudinov requested changes
Хорошо справился
Теперь подправь пж замечания в комментариях и сделай пж этот блок адаптивным для всех разрешений
Пусть будет только один брейкпоинт примерно на 1000 пикселей, чтобы не тратить на адаптив много времени

2022-11-25 19:38 UTC, andrey-kudinov commented on index.html
> +          <h1 class="main_title">Be surprised</h1>
Вряд ли это будет `h1` в каком либо из лендингов, где компонент заюзается
`h2` или `h3`

2022-11-25 19:38 UTC, andrey-kudinov commented on index.html
> +      <div class="contaianer main_container">
Семантически лучше тег `section`

2022-11-25 19:38 UTC, andrey-kudinov commented on index.html
> +            <img src="img/main_bg.jpg" alt="background_img">
Старайся использовать преттиер чтобы везде были одинаковые отступы

2022-11-25 19:38 UTC, andrey-kudinov commented on main.css
> +    justify-content: space-between;
Я думаю это свойство не обязательно
Без него не должно ничего поменяться

2022-11-25 19:38 UTC, andrey-kudinov commented on main.css
> +.main_img {
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/64890665/204046430-5b983b0c-15f7-4b7b-b5ee-4ad04309f932.png">
Смотри, я обернул родительский блок в бордер и под картинкой есть пространство
Если хочешь, можешь сам решить эту проблему или я могу объяснить

2022-11-25 19:38 UTC, andrey-kudinov commented on main.css
> +
Лишняя пустая строка

2022-11-25 19:38 UTC, andrey-kudinov commented on main.css
> +    }
Лучше использовать преттиер

2022-11-25 19:38 UTC, andrey-kudinov commented on main.css
> +    font-size: 16px;
Для шрифтов лучше использовать rem, так как тогда браузеры будут поддерживать изменение размера шрифта

2022-11-26 15:06 UTC, dmitrykorochkin commented on index.html
> +          <h1 class="main_title">Be surprised</h1>
> Поправил, брйекпоинт поменьше может сделать? 800 например, на 1000 вроде норм все

2022-11-26 16:59 UTC, andrey-kudinov approved these changes

2022-11-26 16:59 UTC, andrey-kudinov commented on index.html
> +      <div class="contaianer main_container">
Вот этот тег можно сделать section
А другую обертку удалить
Меньше оберток - быстрее работает
Но конечно тут не будет заметно конечно, просто как паттерн
Сори за занудство

2022-11-26 16:59 UTC, andrey-kudinov commented on index.html
> +          <div class="main_descr">
Я думаю это тег параграфа

2022-11-26 16:59 UTC, andrey-kudinov commented on index.html
> +          <img src="img/main_bg.jpg" alt="background_img" />
Такой альт будет сложновато прочитать скрин ридеру
Можно описать содержимое
Мужчина в очках

2022-11-26 16:59 UTC, andrey-kudinov commented on main.css
> +  display: block;
👍

2022-11-27 06:28 UTC, merged